sudo: required
language: rust
rust:
  - nightly
os:
  - linux
#  - osx
dist: trusty
before_install:
    - if [ `uname` = "Linux" ]; then
        sudo apt-get install -qq nasm pkg-config fuse libfuse-dev;
        sudo modprobe fuse;
        sudo chmod 666 /dev/fuse;
        sudo chown root:$USER /etc/fuse.conf;
      fi
    - if [ `uname` = "Darwin" ]; then
        brew update;
        brew install nasm gcc49 pkg-config Caskroom/cask/osxfuse;
        brew tap glendc/gcc_cross_compilers;
        brew install glendc/gcc_cross_compilers/x64-elf-binutils glendc/gcc_cross_compilers/x64-elf-gcc;
      fi
script:
  - make clean
  - make all -j 2
notifications:
  email: false
  webhooks: http://37.139.9.28:54863/travis
  
