sudo: required
language: rust
rust:
  - nightly
os:
  - linux
  - osx
before_install:
    - if [ `uname` = "Darwin" ]; then
        brew tap nashenas88/gcc_cross_compilers;
        brew update;
        brew unlink gcc;
        brew install nashenas88/gcc_cross_compilers/x86_64-elf-binutils nashenas88/gcc_cross_compilers/x86_64-elf-gcc nasm;
      fi
    - if [ `uname` = "Linux" ]; then
        sudo apt-get install -qq nasm pkg-config fuse;
        sudo modprobe fuse;
        sudo chmod 666 /dev/fuse;
        sudo chown root:$USER /etc/fuse.conf;
      fi
script:
  - make clean
  - make all -j 3
notifications:
  email: false
  webhooks: http://37.139.9.28:54863/travis
#branches:
#  only:
#    - auto
