[package]
name = "libc"
version = "0.1.0"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
build = "../../rust/src/rustc/libc_shim/build.rs"

[lib]
name = "libc"
path = "../../rust/src/liblibc/src/lib.rs"
test = false
bench = false
