[[drivers]]
name = "E1000 NIC"
class = 2
vendor = 32902
device = 4110
command = ["e1000d", "$BAR0", "$IRQ"]

[[drivers]]
name = "RTL8168 NIC"
class = 2
vendor = 4332
device = 33128
command = ["rtl8168d", "$BAR2", "$IRQ"]
