[package]
name = "tcpd"
version = "0.1.0"

[dependencies]
event = { path = "../../crates/event/" }
netutils = { path = "../../programs/netutils/" }
rand = { git = "https://github.com/redox-os/rand.git" }
syscall = { path = "../../syscall/" }
